spring:
  datasource:
    url: jdbc:sqlite:./data/recorder.sqlite
    driver-classname: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
  executor:
    threadpool:
      core-size: 2
      max-size: 3
allowed:
  simultaneous:
    streams: 1
server:
  port: 8084
application:
  security:
    api-key: ${API_KEY}
management:
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.boot.autoconfigure: WARN
    org.springframework.security: WARN
    org.apache.coyote: WARN
recorder:
  recording-folder-prefix: /recordings/